name: Publish 'latest' image

on:
  release:
    types:
      - "created"

jobs:
  archipelago-core-deployment:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-release.yml@main
    with:
      service-name: archipelago-prometheus-nats-exporter
      image-name: archipelago-prometheus-nats-exporter
      deployment-environment: prd
    secrets: inherit
